port: 8080

proxyServer: "http://localhost:80"

redis:
  address: "localhost:6379"
  password: ""
  database: 0

rateLimiterMode: 1

rateLimiter:
  tokenBucket:
    maxToken: 3
    tokenPerSecond: 3
  leakyBucket:
    capacity: 4
    leakyPerSecond: 1
  fixedWindow:
    windowSize: 2
    maxRequests: 5
  slideWindow:
    windowSize: 2
    maxRequests: 5

