server: "http://localhost"

port: 8080

proxyServer: "http://localhost:80"

jwtSetting:
  secretKey: "www.supercat.cc"

redis:
  address: "localhost:6379"
  password: ""
  database: 0

rateLimiterMode: 1

rateLimiter:
  maxCounter: 3
  tokenBucket:
    maxToken: 3
    tokenPerSecond: 1
  leakyBucket:
    capacity: 30
    leakyPerSecond: 10
  fixedWindow:
    windowSize: 1
    maxRequests: 20
  slideWindow:
    windowSize: 1
    maxRequests: 10

